### PR TITLE
Napari join labels

### PR DESCRIPTION
**Pull request by maliagehan**
**Describe your changes**
A clear and concise description of what changes are made by this pull request.
What was the previous functionality (if relevant) and what can we do now with
these changes.

**Type of update**
Is this a:
* New feature or feature enhancement
* Update to documentation

**Associated issues**
Reference associated issue numbers. Does this pull request close any issues? #12 

**Additional context**

**For the reviewer**
See [this page](https://plantcv.readthedocs.io/en/latest/pr_review_process/) for instructions on how to review the pull request.
- [x] PR functionality reviewed in a Jupyter Notebook
- [x] All tests pass
- [x] Test coverage remains 100%
- [x] Documentation tested
- [x] New documentation pages added to `plantcv/mkdocs.yml`
- [ ] Changes to function input/output signatures added to `updating.md`
- [x] Code reviewed
- [x] PR approved

### CODE REVIEW

**Comment by maliagehan** [comment]
notebooks to test are available on workspace jupyter>pcv-annotate-prs>pr13-napari-join-labels

**Comment by maliagehan** [comment]
Realized by adding the printing option that I should save that out to a temp file in the test, will update that

**Review by k034b363 — APPROVED** [review]
Plantcv-annotate doesn't yet have an updating.md, so these changes would need to be added to that if it is created later. Notebook used for testing functionality stored in data_science/jupyter/pcv-annotate-prs/pr13-napari-join-labels/review_materials_KB/

**Comment by HaleySchuhl** [comment]
I believe the `changelog.md` is serving the same purpose as `updating.md` in the add-on repositories, so we can add new functions there. And then once it's packaged up on Conda and/or pip then we might want to add a doc page for versioning.

**Comment by nfahlgren** [comment]
I changed the name to `changelog` for the add-on packages because that's really what we use the `updating` page for. I don't think we need a separate page for versioning as we don't really use the existing page for that per se.

**Pull request merged**
